export const FETCH_MY_ALL_ITEM_LIST = 'FETCH_MY_ALL_ITEM_LIST';
export const FETCH_MY_PROFILE = 'FETCH_MY_PROFILE';
export const FETCH_SEARCH_USER_LIST = 'FETCH_SEARCH_USER_LIST';
export const ADD_FOLLOW_LIST = 'ADD_FOLLOW_LIST';
export const REMOVE_FOLLOW_LIST = 'REMOVE_FOLLOW_LIST';