export default {
    userId: '5ded64280ee4351ae8dbc6d2',
    token: localStorage.getItem('wishToken') || '',
    sid:'',
    myProfile:{},
    myFollowings: [],
    myFollowers: [],
    myAllItemList: [],
    myItemList: [],
    myDoneList: [],
    searchUserList:[],
    othersFollowings: [],
    othersFollowers: [],
    othersItemList: [],
    othersDoneList: [],
    loading: false,
}